GET http://localhost:8080/api/v1/app/movies
###
POST http://localhost:8080/api/v1/app/movies
###
POST http://localhost:8080/api/v1/app/theaters
###
POST http://localhost:8080/api/v1/app/movie
Content-Type: application/json

{
  "movieName" : "스파이더맨"
}
###
POST http://localhost:8080/api/v1/app/theater
Content-Type: application/json

{
  "theaterName" : "강변"
}
###
POST http://localhost:8080/api/v1/app/reservation
Content-Type: application/json

{
  "theaterName" : "강변",
  "movieTitle" : "해적",
  "time" :  "1400"
}